# Use a imagem oficial do PHP 7.4 com Apache
FROM php:7.4-apache

# Instale extensões do PHP necessárias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copie os arquivos do aplicativo para o diretório de trabalho do Apache
COPY ./ /var/www/html/

# Defina permissões adequadas
RUN chown -R www-data:www-data /var/www/html/
RUN chmod -R 755 /var/www/html/

# Exponha a porta 80
EXPOSE 80
